name: mobility
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter

  firebase_core: ^3.14.0
  google_fonts: ^4.0.4
  geolocator: ^10.0.0
  geocoding: ^2.1.0

  google_maps_flutter: ^2.4.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  flutter_gen: ^5.3.2
  flutter_screenutil: ^5.9.0
  injectable: ^2.3.2
  dartz: ^0.10.1
  flutter_polyline_points:
  google_places_flutter:

  dio: ^4.0.6

  http: ^1.1.0
  dropdown_button2: ^2.3.9
  firebase_database: ^11.3.7
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  google_sign_in: ^6.3.0
  connectivity_plus: ^6.1.4
  url_launcher: ^6.3.1
  flutter_steps: ^1.0.5
  infinite_scroll_pagination: ^5.1.0
  flutter_native_splash: ^2.4.6
  
  

dev_dependencies: 
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

flutter: 
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/app/assets/


  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

scripts:
  gen-build: "dart run build_runner build"
  gen-watch: "dart run build_runner watch"
  build: ".fvm/flutter_sdk/bin/flutter build apk --split-per-abi"
  gen-assets: "fluttergen -c pubspec.yaml && dart run build_runner build"

splash:
    - dart pub run flutter_native_splash:remove --path=splash.yaml
    - dart pub run flutter_native_splash:create --path=splash.yaml