// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjNbSyNHoE32v4hRJPhp4AS0f4txN_kQ',
    appId: '1:714842411456:web:3a89b1636a00787e45f825',
    messagingSenderId: '714842411456',
    projectId: 'mobilityplus-74105',
    authDomain: 'mobilityplus-74105.firebaseapp.com',
    storageBucket: 'mobilityplus-74105.appspot.com',
    measurementId: 'G-TEZPQ3712Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvuZ47B67_Es0vDaakG_tooRyi2cFaU38',
    appId: '1:714842411456:android:95c9a6dfc770968345f825',
    messagingSenderId: '714842411456',
    projectId: 'mobilityplus-74105',
    storageBucket: 'mobilityplus-74105.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSBWmU7p_y7wPfvZI98S6hypnDXT5aF34',
    appId: '1:714842411456:ios:64ac143c6d70165d45f825',
    messagingSenderId: '714842411456',
    projectId: 'mobilityplus-74105',
    storageBucket: 'mobilityplus-74105.appspot.com',
    androidClientId:
        '714842411456-1ggk35rib0r3b7ofpphlvel8np5baj06.apps.googleusercontent.com',
    iosClientId:
        '714842411456-8tai06ha4jpmab72qgepgjh92ohitr9m.apps.googleusercontent.com',
    iosBundleId: 'com.mobility.mobility',
  );
}
